# video in
-f v4l2
-thread_queue_size 8192
-s 640x480
-i /dev/video0

# audio in
-f alsa
-thread_queue_size 8192
-i hw:3,0

# video out
-c:v h264_v4l2m2m
-pix_fmt yuv420p
-b:v 200k
-s 320x240
-r 15

# audio out
-c:a aac
-b:a 64k
-ac 1
-ar 44100

# muxed out
-f flv
